.PHONY: clear

clear:
	rm *.out

sig.out: sig.c
	gcc sig.c -o sig.out
	./sig.out

tube.out: tube.c
	gcc tube.c -o tube.out
	./tube.out

c1.out: c1.cpp
	g++ c1.cpp -o c1.out
	./c1.out

d.out: d.cpp
	g++ d.cpp -o d.out
	./d.out

page.out: page.cpp
	g++ page.cpp -o page.out -ggdb -std=c++11
	./page.out